spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 7801106414-1vtfsjdr0p4hh6p39favpvtd1r0bqid8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
